locationnames = [

#WHISPERING ROCK SUMMER CAMP
#Sasha's Underground Lab (CASA)
"Behind Furniture (Card)",
"Staircase Ledges (Card)",
"Upper Ledge (Fossil)",
#GPC and Wilderness (CAGP)
"Top of GPC (Card)",
"Under GPC (Card)",
"Mountain Lion Log Bridge (Card)",
"Above Entrance to Lake (Card)",
"Rock Wall Behind Tree (Card)",
"Rock Wall Top (Pirate Scope)",
"Tree Near Fence (Card)",
"Tree Near Geyser (Card)",
"Fence Behind GPC (Card)",
"Near the Bear (Card)",
"Rocky Platforms Behind GPC Right (Card)",
"Rocky Platforms Behind GPC Left (Card)",
"Top of Log Flume (Card)",
"Ride the Log Flume (Card)",
"Bottom of Log Flume (Card)",
"Big Rock Near Ford (Card)",
"Ruined Cabin (Challenge Marker)",
"Branch Swinging Course Start (Card)",
"Branch Swinging Course Mid (Card)",
"Branch Swinging Course End (Challenge Marker)",
"Branch Above Squirrel (Card)",
"Creek Grate (Glass Eye)",
"Squirrel's Acorn (Golden Acorn)",
"Geyser (Miner's Skull)",
#Main Campgrounds (CAMA)
"Fence Near Kids' Cabins (Card)",
"Under Lodge Front Steps (Card)",
"Behind Tree Near Lodge (Card)",
"Under the Lodge (Gold Doubloon)",
"Loudspeaker 1 Platform  (Card)",
"Under Lodge Metal Roof (Card)",
"Loudspeaker Tightrope Walk (Card)",
"Loudspeaker 2 Platform (Card)",
"Lodge Roof (Challenge Marker)",
"Metal Roof Outcropping (Card)",
"Loudspeaker Above Stump (Card)",
"Tree Platform Left (Card)",
"Tree Platform Right (Eagle Claw)",
"Rock Wall Top (Card)",
"Parking Lot Arch (Card)",
"Parking Lot Small Log (Card)",
"Oleander's Car (Card)",
"Parking Lot Basketball Hoop (Card)",
"Parking Lot History Board (Card)",
"Parking Lot Outhouse (Card)",
"Rock Near Bench (Card)",
#Kids' Cabins (CAKC)
"Grinding on the Roots (Card)",
"Under Stairs (Card)",
"Top of Loudspeaker (Card)",
"Cabin Roof 1 (Card)",
"Trampoline Above Outhouse (Card)",
"Trampoline Platform (Challenge Marker)",
"Cabins Outhouse (Card)",
"Behind Cabin (Card)",
"Roof of Cabin 2 (Card)",
"Cave Entrance (Card)",
"Deep Cave Path (Card)",
"Deep Cave Ladder (Card)",
"High-Up Tightrope (Card)",
"Cave Refrigerator (Turkey Sandwich)",
#Reception Area (CARE)
"Graveyard Bear (Card)",
"Near Beehive (Card)",
"Mineshaft Trailer Entrance (Card)",
"Tightrope Start (Card)",
"Tightrope End (Card)",
"Rocks Near Trailer (Card)",
"Fireplace Tree Lower (Card)",
"Fireplace Tree Rock (Card)",
"Swamp Skinny Poles (Card)",
"Big Log Platform (Card)",
"Above Waterfall Left (Card)",
"Above Waterfall Right (Card)",
"Behind the Waterfall (Card)",
"Weird Tree Left (Cherry Wood Pipe)",
"Weird Tree Right (Card)",
"Log Hill Top (Card)",
"Log Hill Behind (Card)",
"Mineshaft Grind Rail (Card)",
"Mineshaft Upper Entrance (Card)",
"Mineshaft Above Upper Entrance (Card)",
"Inside Mineshaft (Card)",
"Mineshaft Bear (Card)",
"Swamp Bird's Nest (Condor Egg)",
"Collapsed Cave (Challenge Marker)",
"Fireplace Tree Top (Dinosaur Bone)",
"Hornet Nest (Fertility Idol)",
#Lake and Boathouse (CABH)
"Under the First Bridge (Card)",
"Behind Stump (Card)",
"Left of Entrance Rock Wall (Card)",
"Poles on Lake (Card)",
"Bathysphere Roof (Card)",
"Bathysphere Dock (Card)",
"Metal Roof Above Ford (Card)",
"Above Ford Ropes (Card)",
"Above Ford Cabin Platform (Card)",
"Outside Cougar Cave (Card)",
"Inside Cougar Cave (Diver's Helmet)",
"Bulletin Board Bushes (Card)",
"Pink Trees Swinging (Card)",
"Pink Trees Platform (Card)",
"Rock Wall Upper (Card)",
"Lake Shore (Card)",
"Tiny Island (Card)",
"Top of Big Rock (Challenge Marker)",
"Rock Wall Gap (Psychonauts Comic #1)",
#Main Lodge (CALI)
"Main Lodge Rafters (Voodoo Doll)",
#Ford's Sanctuary (CAJA)
"Top of Sanctuary (Card)",
"Bottom of Sanctuary (Card)",
#Rando Only Rank Checks
"PSI Rank 05",
"PSI Rank 10",
"PSI Rank 15",
"PSI Rank 20",
"PSI Rank 25",
"PSI Rank 30",
"PSI Rank 35",
"PSI Rank 40",
"PSI Rank 45",
"PSI Rank 50",
"PSI Rank 55",
"PSI Rank 60",
"PSI Rank 65",
"PSI Rank 70",
"PSI Rank 75",
"PSI Rank 80",
"PSI Rank 85",
"PSI Rank 90",
"PSI Rank 95",
"PSI Rank 100",

#THORNEY TOWERS
#Asylum Grounds (ASGR)
"Rock Wall Bottom (Lili's Bracelet)",
"Rock Wall Ladder (Card)",
"Outside Front Gate (Challenge Marker)",
"Pillar Above Gate (Card)",
"Fountain Top (Gold Watch)",
"Hedge Alcove (JT's Brain)",
"Asylum Doors Right (Franke's Brain)",
"Asylum Doors Left (Card)",
"Corner Near Fence (Card)",
"Ledge Before Gloria (Kitty's Brain)",
#Asylum Lower Level (ASCO)
"Above Elevator (Card)",
"Crow's Basket (Milka's Brain)",
"Ledge Above Fred Left (Chops' Brain)",
"Ledge Above Fred Right (Card)",
"Ledge Opposite Elevator (Card)",
"Edgar's Room (Card)",
"Behind Elevator (Maloof's Brain)",
"Junk Corner (Chloe's Brain)",
"Above Edgar (Challenge Marker)",
#Asylum Upper Level (ASUP)
"Behind Mattress Wall (Card)",
"Checkered Bathroom (Benny's Brain)",
"Room Near Checkered Bathroom (Card)",
"Elevator Shaft (Card)",
"Room Left of Pipe Slide (Bobby's Brain)",
"Floating in Hole (Card)",
"Next to Hole (Card)",
"Crumbling Outer Wall Planks (Elka's Brain)",
"Crumbling Outer Wall Pillar (Card)",
"Crumbling Outer Wall Below Platform (Card)",
"Crumbling Outer Wall Platform (Card)",
"Room Above Tilted Stairs (Card)",
"Acid Room Floor (Card)",
"Acid Room Table (Card)",
"Acid Room Window (Quentin's Brain)",
"Acid Room Overhang (Card)",
"Small Windows Ledge (Dogen's Brain)",
"Round Wood Platform (Card)",
"Grate Climb Bottom (Phoebe's Brain)",
"Grate Climb Mid (Card)",
"Sink Platform Left (Card)",
"Sink Platform Right (Crystal's Brain)",
"Pipes Below Chair Door (Challenge Marker)",
"Room Opposite Chair Door (Clem's Brain)",
"Pipe Slide Near Chair Door (Card)",
"Rafters Above Chair Door (Nil's Brain)",
#Dr. Loboto's Laboratory (ASLB)
"Lab Caged Crow Left (Card)",
"Lab Caged Crow Right (Vernon's Brain)",
"Next to Pokeylope (Card)",
"Lab Top Railing Left 1 (Card)",
"Lab Top Railing Left 2 (Jarred Brain)",
"Lab Top Elevator (Jarred Brain)",
"Lab Top Railing Right (Card)",
"Tea Room (Birthday Cake)",

#BASIC BRAINING
#Obstacle Course 1 (BBA1)
"Jumping Tutorial 1 (Steamer Trunk)",
"Jumping Tutorial 2 (Steamer Trunk Tag)",
"Pole-Climbing Tutorial Floor (Suitcase Tag)",
"Below the Triple Trampolines (Suitcase)",
#Obstacle Course 2 (BBA2)
"Giant Soldier Cut-Out (Vault)",
"Dodging Bullets 1 (Hatbox Tag)",
"Dodging Bullets 2 (Hatbox)",
"Machine Gun Turret (Dufflebag Tag)",
"Pole-Swinging Tutorial (Dufflebag)",
"Trapeze Cobweb (Vault)",
"Trapeze Platform (Purse Tag)",
"Inside Plane Wreckage (Purse)",
#Obstacle Course Finale (BBLT)
"End of Obstacle Course Left",
"End of Obstacle Course Right",
"Basic Braining Complete",

#SASHA'S SHOOTING GALLERY
#Cube Face 1 (SACU)
"On the Bed (Memory Vault)",
"On the Pillow (Dufflebag Tag)",
"Building Blocks Left (Hatbox Tag)",
"Building Blocks Below (Dufflebag)",
"Building Blocks Right (One-Up)",
"Top of Bed Frame (Hatbox)",
#Cube Face 2 (SACU)
"Round Platforms Bottom (Purse Tag)",
"Round Platforms Near Valve (Purse)",
"Round Platforms Far from Valve (One-Up)",
#Cube Face 3 (SACU)
"Side of Cube Face 3 (Vault)",
"Bottom of Shoebox Ladder (Steamer Trunk Tag)",
"Shoebox Pedestal (Steamer Trunk)",
"Shoebox Tower Top (One-Up)",
#Cube Face 4 (SACU)
"Flame Tower Steps (Suitcase Tag)",
"Flame Tower Top 1 (Suitcase)",
"Flame Tower Top 2 (One-Up)",
"Sasha's Shooting Gallery Complete",

#MILLA'S DANCE PARTY
#The Lounge (MIFL)
"Intro Rings Tutorial (Dufflebag Tag)",
"Dancing Camper Platform 1 (Dufflebag)",
"Demon Room (Memory Vault)",
"Windy Ladder Bottom (Steamer Trunk Tag)",
"Pinball Plunger (Hatbox Tag)",
"Plunger Party Ledge (Steamer Trunk)",
"Grindrail Rings (Hatbox)",
"Censor Hallway (Purse Tag)",
"Pink Bowl Bottom (Vault)",
"Pink Bowl Small Platform (Purse)",
#The Party (MILL)
"Bubbly Fan Bottom (Suitcase Tag)",
"Bubbly Fan Platform (Ammo Upgrade)",
"Bubbly Fan Top (Suitcase)",
"Milla's Party Room",
"Milla's Dance Party Complete",

#BRAIN TUMBLER EXPERIMENT
#The Nightmare Woods (NIMP)
"Outside Caravan (Vault)",
"Behind the Egg (Purse Tag)",
"Shadow Monster Path (Steamer Trunk Tag)",
"Shadow Monster Blue Mushrooms (Purse)",
"Ledge Behind Shadow Monster (Steamer Trunk)",
"Below the Steep Ledge (Dufflebag Tag)",
"Forest Path Blue Mushrooms (Suitcase Tag)",
"Forest Blue Ledge (Suitcase)",
"Forest High Platform (Dufflebag)",
"Forest Path Thorns (Hatbox Tag)",
"Behind Thorn Tower Left (Hatbox)",
"Behind Thorn Tower Mid (Max Lives)",
"Behind Thorn Tower Right (Vault)",
#The Brain Tank (NIBA)
"Brain Tumbler Experiment Complete",

#LUNGFISHOPOLIS
#Lungfishopolis City (LOMA)
"Skyscraper Start (One Up)",
"Corner Near Jail (Dufflebag)",
"Skyscraper before Dam (Purse Tag)",
"Behind Lasers Left 1 (Dufflebag Tag)",
"Behind Lasers Left 2 (Vault)",
"Behind Lasers Right (Purse)",
"Blimp Hop (Hatbox Tag)",
"End of Dam (Hatbox)",
"End of Dam Platform (One Up)",
"Skyscraper after Dam (Ammo Up)",
"Near Battleships (Steamertrunk Tag)",
"On the Bridge (One Up)",
"Ground after Bridge (Vault)",
"Skyscraper after Bridge (Steamertrunk)",
"Tunnel (Suitcase Tag)",
"Final Skyscrapers Left (Max Lives)",
"Final Skyscrapers Right (Suitcase)",
#Kochamara Arena (LOCB)
"Kochamara Intro Left",
"Kochamara Intro Right",
"Lungfishopolis Complete",

#THE MILKMAN CONSPIRACY
#The Neighborhood 1 (MMI1)
"Boyd's Fridge (Clairvoyance)",
"First House (Dufflebag Tag)",
"Second House (Rolling Pin)",
"Car Trunk 1 (Stop Sign)",
"Roof after Road Crew  (Purse Tag)",
"Car Trunk 2 (Hedge Trimmers)",
"Car House Backyard (Steamertrunk Tag)",
"Inside Webbed Garage (Hatbox)",
"Graveyard Patio (Vault)",
"Graveyard Behind Tree (One Up)",
"Behind Graveyard (Dufflebag)",
"Hedge Maze (Flowers)",
"Car Trunk 3 (Watering Can)",
"Post Office Roof (One Up)",
"Post Office Lobby (Suitcase)",
"Post Office Basement (Plunger)",
"Landscapers House Backyard (Suitcase Tag)",
"Landscapers House Table (Purse)",
"Landscapers House Kitchen (Ammo Up)",
"Powerline Island Sandbox (Hatbox Tag)",
"Powerline Island Left (Memory Vault)",
"Powerline Island Right (Max Lives)",
#The Neighborhood 2 (MMI2)
"Behind Book Depository (Steamer Trunk)",
"Milkman Complete",

#GLORIA'S THEATER
#The Stage (THMS)
"Near the Critic (Purse)",
"In the Audience (Ammo Up)",
"Below the Spotlight (Steamertrunk Tag)",
"Behind Stage (Purse Tag)",
"Behind Stage Cobweb (Suitcase)",
"Storage Room Floor (Vault)",
"Storage Room Left (Steamertrunk)",
"Storage Room Right Lower (Suitcase Tag)",
"Storage Room Right Upper (Candle #1)",
"Bonita's Room",
#The Catwalks (THCW)
"Doghouse Slicers (Dufflebag Tag)",
"Big Platform 1 (Hatbox)",
"Big Platform 2 (Vault)",
"Big Platform 3 (One Up)",
"Big Platform Above (Hatbox Tag)",
"Next to Oatmeal (Dufflebag)",
"Candle Basket (Candle #2)",
"Catwalks Start",
"After Trampolines",
"Gloria's Theater Complete",

#WATERLOO WORLD (WWMA)
"Fred's Room (Hatbox Tag)",
"The Fireplace (Priceless Coin)",
"Game Board (Suitcase Tag)",
"Carpenter's Roof (Vault)",
"Tightrope Room (Dufflebag)",
"Outside Villager 1 House (One Up)",
"Small Arch Top (Max Lives)",
"Small Arch Below (Purse Tag)",
"Top of Villager 2's House (Dufflebag Tag)",
"Top of Villager 3's House (Ammo Up)",
"Castle Tower (One Up)",
"Castle Inside (Vault)",
"Castle Wall (Steamertrunk)",
"Under the Guillotine (Suitcase)",
"Fred's House Basement (Hatbox)",
"Blacksmith's Left Building (Purse)",
"Blacksmith's Right Building (Steamertrunk Tag)",
"Blacksmith's Haybale (The Musket)",
"Help the Carpenter",
"Help Villager 1",
"Help the Knight",
"Help Villager 2",
"Help Villager 3",
"Waterloo World Complete",

#BLACK VELVETOPIA
#Running Against the Bull (BVRB)
"Club Street Lady (Steamertrunk)",
"Club Street Metal Balcony (Dufflebag Tag)",
"Heart Street HIGH Balcony (Ammo Up)",
"Alleyways Ledge (Hatbox Tag)",
"Sewers Main (Vault)",
"Club Street Gated (Steamer Trunk Tag)",
"Burn the Logs (Dufflebag)",
"The Garden (Vault)",
"Near Diego's House (Max Lives)",
"Diego's Bed (Suitcase Tag)",
"Diego's Room (Hatbox)",
"Diego's House Grindrail (Suitcase)",
#Edgar's Sanctuary (BVES)
"Sanctuary Balcony (Purse Tag)",
"Sanctuary Ground (Purse)",
"Tiger Wrestler",
"Dragon Wrestler",
"Eagle Wrestler",
"Cobra Wrestler",
"Black Velvetopia Complete",

#MEAT CIRCUS
#Meat Circus Main (MCTC)
"Entrance Awning (Steamertrunk Tag)",
"Crumbling Path (Steamertrunk)",
"Crumbling Path End (Hatbox Tag)",
"Ollie Escort Floor (Suitcase Tag)",
"Ollie Escort Middle (Hatbox)",
"Ollie Escort Top Left (Vault)",
"Ollie Escort Top Right (Purse Tag)",
"Tunnel of Love Start (Purse)",
"Tunnel of Love Corner (Suitcase)",
"Tunnel of Love Rail (Dufflebag Tag)",
"Next to the Fat Lady (Dufflebag)",

]