function Positions(Ob)
    if ( not Ob ) then
        Ob = CreateObject('ScriptBase')
        --[[list of all check positions in the game,
        special case items should go at end of list]]
        Ob.positionsList = {}
    end

    function Ob:fillTable()
        local posTable ={


            --*******************************************************--
            --CA, CAMPGROUNDS

            --CASA, Sasha's Lab
            item1 = {        
                levelName = 'CASA',
                x = 1032, 
                y = 8, 
                z = -1478,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item2 = {        
                levelName = 'CASA',
                x = 505, 
                y = 846, 
                z = 1587,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item3 = {        
                levelName = 'CASA',
                x = 20, 
                y = 1907, 
                z = -1810,
                ox = 0,
                oy = 0,
                oz = 0,
            },

            --CAGP, GPC & Wilderness
            item4 = {        
                levelName = 'CAGP',
                x = 6257, 
                y = 2282, 
                z = -5951,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item5 = {        
                levelName = 'CAGP',
                x = 7253, 
                y = 556, 
                z = -7460,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item6 = {        
                levelName = 'CAGP',
                x = 2955, 
                y = 866, 
                z = -2113,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item7 = {        
                levelName = 'CAGP',
                x = 8571, 
                y = 628, 
                z = -9,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item8 = {        
                levelName = 'CAGP',
                x = 10620, 
                y = 1122, 
                z = -1017,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item9 = {        
                levelName = 'CAGP',
                x = 11570, 
                y = 1996, 
                z = -2299,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item10 = {        
                levelName = 'CAGP',
                x = 9382, 
                y = 460, 
                z = -6267,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item11 = {        
                levelName = 'CAGP',
                x = 10946, 
                y = 78, 
                z = -6199,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item12 = {        
                levelName = 'CAGP',
                x = 8753, 
                y = 621, 
                z = -8998,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item13 = {        
                levelName = 'CAGP',
                x = 6018, 
                y = 607, 
                z = -9088,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item14 = {        
                levelName = 'CAGP',
                x = 3200, 
                y = 1086, 
                z = -8546,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item15 = {        
                levelName = 'CAGP',
                x = 1626, 
                y = 1730, 
                z = -7104,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item16 = {        
                levelName = 'CAGP',
                x = 266, 
                y = 2537, 
                z = -5568,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item17 = {        
                levelName = 'CAGP',
                x = -1400, 
                y = 1815, 
                z = -4198,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item18 = {        
                levelName = 'CAGP',
                x = -3200, 
                y = -85, 
                z = -2505,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item19 = {        
                levelName = 'CAGP',
                x = 1798, 
                y = 1349, 
                z = -3488,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item20 = {        
                levelName = 'CAGP',
                x = 67, 
                y = 666, 
                z = -4448,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item21 = {        
                levelName = 'CAGP',
                x = 5703, 
                y = 2543, 
                z = -7240,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item22 = {        
                levelName = 'CAGP',
                x = 7571, 
                y = 2747, 
                z = -5830,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item23 = {        
                levelName = 'CAGP',
                x = 6913, 
                y = 4212, 
                z = -4829,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item24 = {        
                levelName = 'CAGP',
                x = 9262, 
                y = 1626, 
                z = -4003,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item25 = {        
                levelName = 'CAGP',
                x = 4900, 
                y = -208, 
                z = -2750,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            --Squirrel Puzzle
            item26 = {        
                levelName = 'CAGP',
                x = 10455, 
                y = 0, 
                z = -3724,
                ox = 0,
                oy = 0,
                oz = 0,
                puzzle = 'squirrel'
            },
            --Two Geysers puzzle
            item27 = {        
                levelName = 'CAGP',
                x = 10498, 
                y = -34, 
                z = -8117,
                ox = 0,
                oy = 0,
                oz = 0,
                puzzle = 'geyser'
            },
            
            --CAMA, Main Campgrounds
            item28 = {        
                levelName = 'CAMA',
                x = -10705, 
                y = 4058, 
                z = 6678,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item29 = {        
                levelName = 'CAMA',
                x = -5943, 
                y = 3684, 
                z = 9192,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item30 = {        
                levelName = 'CAMA',
                x = -1053, 
                y = 4746, 
                z = 11808,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item31 = {        
                levelName = 'CAMA',
                x = -4279, 
                y = 4537, 
                z = 6901,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item32 = {        
                levelName = 'CAMA',
                x = -681, 
                y = 5333, 
                z = 8911,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item33 = {        
                levelName = 'CAMA',
                x = -3949, 
                y = 6050, 
                z = 6485,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item34 = {        
                levelName = 'CAMA',
                x = -3423, 
                y = 6213, 
                z = 5171,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item35 = {        
                levelName = 'CAMA',
                x = -4785, 
                y = 6022, 
                z = 3596,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item36 = {        
                levelName = 'CAMA',
                x = -4655, 
                y = 6811, 
                z = 6408,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item37 = {        
                levelName = 'CAMA',
                x = -4452, 
                y = 5881, 
                z = 8571,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item38 = {        
                levelName = 'CAMA',
                x = -9584, 
                y = 5164, 
                z = 12869,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item39 = {        
                levelName = 'CAMA',
                x = -13491, 
                y = 3037, 
                z = 13218,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item40 = {        
                levelName = 'CAMA',
                x = -13157, 
                y = 2954, 
                z = 13652,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item41 = {        
                levelName = 'CAMA',
                x = -14181, 
                y = 2745, 
                z = 16862,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item42 = {        
                levelName = 'CAMA',
                x = -19302, 
                y = 2531, 
                z = 16941,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item43 = {        
                levelName = 'CAMA',
                x = -18501, 
                y = 228, 
                z = 18020,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item44 = {        
                levelName = 'CAMA',
                x = -18284, 
                y = 899, 
                z = 20236,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item45 = {        
                levelName = 'CAMA',
                x = -23384, 
                y = 504, 
                z = 19359,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item46 = {        
                levelName = 'CAMA',
                x = -20810, 
                y = 977, 
                z = 19992,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item47 = {        
                levelName = 'CAMA',
                x = -20821, 
                y = 1018, 
                z = 14518,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item48 = {        
                levelName = 'CAMA',
                x = -14761, 
                y = 1839, 
                z = 12529,
                ox = 0,
                oy = 0,
                oz = 0,
            },

            --CAKC, Kids Cabins
            item49 = {          
                levelName = 'CAKC',
                x = -3621, 
                y = 5509, 
                z = -11089,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item50 = {            
                levelName = 'CAKC',
                x = -5629,   
                y = 4510, 
                z = -13242,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item51 = {        
                levelName = 'CAKC',
                x = -3861, 
                y = 5656, 
                z = -12938,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item52 = {        
                levelName = 'CAKC',
                x = -4437,   
                y = 5240, 
                z = -15717,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item53 = {        
                levelName = 'CAKC',
                x = -5826,   
                y = 5921, 
                z = -17086,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item54 = {        
                levelName = 'CAKC',
                x = -5282, 
                y = 7580, 
                z = -17131,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item55 = {
                levelName = 'CAKC',
                x = -6662,   
                y = 4834, 
                z = -16859,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item56 = {        
                levelName = 'CAKC',
                x = -8250,   
                y = 4672, 
                z = -17194,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item57 = {        
                levelName = 'CAKC',
                x = -8245,   
                y = 5489, 
                z = -16566,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item58 = {        
                levelName = 'CAKC',
                x = -8241, 
                y = 6295, 
                z = -18064,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item59 = {
                levelName = 'CAKC',
                x = -6797,   
                y = 3365, 
                z = -16380,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item60 = {            
                levelName = 'CAKC',
                x = -8613,   
                y = 3409, 
                z = -15159,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item61 = {        
                levelName = 'CAKC',
                x = -9914, 
                y = 8434, 
                z = -18209,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            --Ice Block Puzzle
            item62 = {        
                levelName = 'CAKC',
                x = -4885, 
                y = 4255, 
                z = -19145,
                ox = 0,
                oy = 0,
                oz = 0,
                puzzle = 'ice'
            },

            --CARE, Reception Area
            item63 = {        
                levelName = 'CARE',
                x = -22146, 
                y = 1329, 
                z = 7063,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item64 = {        
                levelName = 'CARE',
                x = -19190, 
                y = 409, 
                z = 2243,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item65 = {        
                levelName = 'CARE',
                x = -16137, 
                y = -161, 
                z = 1986,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item66 = {        
                levelName = 'CARE',
                x = -16401, 
                y = 1240, 
                z = 2029,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item67 = {        
                levelName = 'CARE',
                x = -18895, 
                y = 743, 
                z = -390,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item68 = {        
                levelName = 'CARE',
                x = -18291, 
                y = 1305, 
                z = -2103,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item69 = {        
                levelName = 'CARE',
                x = -17152, 
                y = 2097, 
                z = -4488,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item70 = {        
                levelName = 'CARE',
                x = -15952, 
                y = 1742, 
                z = -4890,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item71 = {        
                levelName = 'CARE',
                x = -13590, 
                y = 1378, 
                z = -5441,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item72 = {        
                levelName = 'CARE',
                x = -14063, 
                y = 1328, 
                z = -6949,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item73 = {        
                levelName = 'CARE',
                x = -12774, 
                y = 1195, 
                z = -7221,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item74 = {        
                levelName = 'CARE',
                x = -10781, 
                y = 1949, 
                z = -8730,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item75 = {        
                levelName = 'CARE',
                x = -11233, 
                y = 119, 
                z = -8485,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item76 = {        
                levelName = 'CARE',
                x = -7218, 
                y = 489, 
                z = -6388,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item77 = {        
                levelName = 'CARE',
                x = -7650, 
                y = 458, 
                z = -5746,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item78 = {        
                levelName = 'CARE',
                x = -9140, 
                y = 1094, 
                z = -3507,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item79 = {        
                levelName = 'CARE',
                x = -8918, 
                y = 319, 
                z = -4513,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item80 = {        
                levelName = 'CARE',
                x = -12076, 
                y = 1170, 
                z = 56,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item81 = {        
                levelName = 'CARE',
                x = -11880, 
                y = 1270, 
                z = 2555,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item82 = {        
                levelName = 'CARE',
                x = -11871, 
                y = 2059, 
                z = 2462,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item83 = {        
                levelName = 'CARE',
                x = -12362, 
                y = 552, 
                z = 5484,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item84 = {        
                levelName = 'CARE',
                x = -14396, 
                y = -981, 
                z = 5422,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item85 = {        
                levelName = 'CARE',
                x = -12376, 
                y = 766, 
                z = -3647,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item86 = {        
                levelName = 'CARE',
                x = -14964, 
                y = 1414, 
                z = -7964,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item87 = {        
                levelName = 'CARE',
                x = -16416, 
                y = 3254, 
                z = -4802,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item88 = {        
                levelName = 'CARE',
                x = -10000, 
                y = -10000, 
                z = -10000,
                ox = 0,
                oy = 178,
                oz = 0,
                puzzle = 'hive'
            },
                        
            --CABH, Lake/Boat House
            item89 = {        
                levelName = 'CABH',
                x = 3817, 
                y = 1411, 
                z = 8836,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item90 = {        
                levelName = 'CABH',
                x = 7382, 
                y = 747, 
                z = 9353,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item91 = {        
                levelName = 'CABH',
                x = 5380, 
                y = 3087, 
                z = 9700,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item92 = {        
                levelName = 'CABH',
                x = 13225, 
                y = 709, 
                z = 10626,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item93 = {        
                levelName = 'CABH',
                x = 14043, 
                y = 1715, 
                z = 14937,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item94 = {        
                levelName = 'CABH',
                x = 13397, 
                y = 378, 
                z = 13652,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item95 = {        
                levelName = 'CABH',
                x = 10974, 
                y = 955, 
                z = 16992,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item96 = {        
                levelName = 'CABH',
                x = 9722, 
                y = 1326, 
                z = 16642,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item97 = {        
                levelName = 'CABH',
                x = 8979, 
                y = 2250, 
                z = 15694,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item98 = {        
                levelName = 'CABH',
                x = 6988, 
                y = 2114, 
                z = 16007,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item99 = {        
                levelName = 'CABH',
                x = 6025, 
                y = 2423, 
                z = 16395,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item100 = {        
                levelName = 'CABH',
                x = 7494, 
                y = 720, 
                z = 13974,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item101 = {        
                levelName = 'CABH',
                x = 9243, 
                y = 1861, 
                z = 6689,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item102 = {        
                levelName = 'CABH',
                x = 4853, 
                y = 2673, 
                z = 11231,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item103 = {        
                levelName = 'CABH',
                x = 7218, 
                y = 2356, 
                z = 7608,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item104 = {        
                levelName = 'CABH',
                x = 12594, 
                y = 375, 
                z = 7903,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item105 = {        
                levelName = 'CABH',
                x = 11949, 
                y = 421, 
                z = 14426,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item106 = {        
                levelName = 'CABH',
                x = 10977, 
                y = 2042, 
                z = 7806,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item107 = {        
                levelName = 'CABH',
                x = 7812, 
                y = 1673, 
                z = 7547,
                ox = 0,
                oy = 0,
                oz = 0,
            },

            --CALI, Lodge Non-Shop Items
            item108 = {        
                levelName = 'CALI',
                x = 7636, 
                y = 984, 
                z = -7760,
                ox = 0,
                oy = -68,
                oz = 0,
            },

            --CAJA, Non-rank spawns
            item109 = {        
                levelName = 'CAJA',
                x = 2498, 
                y = 1670, 
                z = -2882,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item110 = {        
                levelName = 'CAJA',
                x = 3029, 
                y = -36, 
                z = -1738,
                ox = 0,
                oy = 0,
                oz = 0,
            },

            --[[RANK UP ITEMS
            Spawns item for every 5 ranks, moved to Main Platform on Rank requirement
            ]]
            --Rank 5
            item111 = {        
                levelName = 'CAJA',
                x = -10000, 
                y = -10000, 
                z = -10000,
                ox = 0,
                oy = 68,
                oz = 0,
                puzzle = 'rank5'
            },
            --Rank 10
            item112 = {        
                levelName = 'CAJA',
                x = -10000, 
                y = -10000, 
                z = -10000,
                ox = 0,
                oy = 68,
                oz = 0,
                puzzle = 'rank10'
            },
            --Rank 15
            item113 = {        
                levelName = 'CAJA',
                x = -10000, 
                y = -10000, 
                z = -10000,
                ox = 0,
                oy = 68,
                oz = 0,
                puzzle = 'rank15'
            },
            --Rank 20
            item114 = {        
                levelName = 'CAJA',
                x = -10000, 
                y = -10000, 
                z = -10000,
                ox = 0,
                oy = 68,
                oz = 0,
                puzzle = 'rank20'
            },
            --Rank 25
            item115 = {        
                levelName = 'CAJA',
                x = -10000, 
                y = -10000, 
                z = -10000,
                ox = 0,
                oy = 68,
                oz = 0,
                puzzle = 'rank25'
            },
            --Rank 30
            item116 = {        
                levelName = 'CAJA',
                x = -10000, 
                y = -10000, 
                z = -10000,
                ox = 0,
                oy = 68,
                oz = 0,
                puzzle = 'rank30'
            },
            --Rank 35
            item117 = {        
                levelName = 'CAJA',
                x = -10000, 
                y = -10000, 
                z = -10000,
                ox = 0,
                oy = 68,
                oz = 0,
                puzzle = 'rank35'
            },
            --Rank 40
            item118 = {        
                levelName = 'CAJA',
                x = -10000, 
                y = -10000, 
                z = -10000,
                ox = 0,
                oy = 68,
                oz = 0,
                puzzle = 'rank40'
            },
            --Rank 45
            item119 = {        
                levelName = 'CAJA',
                x = -10000, 
                y = -10000, 
                z = -10000,
                ox = 0,
                oy = 68,
                oz = 0,
                puzzle = 'rank45'
            },
            --Rank 50
            item120 = {        
                levelName = 'CAJA',
                x = -10000, 
                y = -10000, 
                z = -10000,
                ox = 0,
                oy = 68,
                oz = 0,
                puzzle = 'rank50'
            },
            --Rank 55
            item121 = {        
                levelName = 'CAJA',
                x = -10000, 
                y = -10000, 
                z = -10000,
                ox = 0,
                oy = 68,
                oz = 0,
                puzzle = 'rank55'
            },
            --Rank 60
            item122 = {        
                levelName = 'CAJA',
                x = -10000, 
                y = -10000, 
                z = -10000,
                ox = 0,
                oy = 68,
                oz = 0,
                puzzle = 'rank60'
            },
            --Rank 65
            item123 = {        
                levelName = 'CAJA',
                x = -10000, 
                y = -10000, 
                z = -10000,
                ox = 0,
                oy = 68,
                oz = 0,
                puzzle = 'rank65'
            },
            --Rank 70
            item124 = {        
                levelName = 'CAJA',
                x = -10000, 
                y = -10000, 
                z = -10000,
                ox = 0,
                oy = 68,
                oz = 0,
                puzzle = 'rank70'
            },
            --Rank 75
            item125 = {        
                levelName = 'CAJA',
                x = -10000, 
                y = -10000, 
                z = -10000,
                ox = 0,
                oy = 68,
                oz = 0,
                puzzle = 'rank75'
            },
            --Rank 80
            item126 = {        
                levelName = 'CAJA',
                x = -10000, 
                y = -10000, 
                z = -10000,
                ox = 0,
                oy = 68,
                oz = 0,
                puzzle = 'rank80'
            },
            --Rank 85
            item127 = {        
                levelName = 'CAJA',
                x = -10000, 
                y = -10000, 
                z = -10000,
                ox = 0,
                oy = 68,
                oz = 0,
                puzzle = 'rank85'
            },
            --Rank 90
            item128 = {        
                levelName = 'CAJA',
                x = -10000, 
                y = -10000, 
                z = -10000,
                ox = 0,
                oy = 68,
                oz = 0,
                puzzle = 'rank90'
            },
            --Rank 95
            item129 = {        
                levelName = 'CAJA',
                x = -10000, 
                y = -10000, 
                z = -10000,
                ox = 0,
                oy = 68,
                oz = 0,
                puzzle = 'rank95'
            },
            --Rank 101
            item130 = {        
                levelName = 'CAJA',
                x = -10000, 
                y = -10000, 
                z = -10000,
                ox = 0,
                oy = 68,
                oz = 0,
                puzzle = 'rank101'
            }, 

            --*******************************************************--
            --AS, THORNEY TOWERS ASYLUM

            --ASGR, Starting Grounds
            item131 = {        
                levelName = 'ASGR',
                x = 184, 
                y = -1498, 
                z = 8893,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item132 = {        
                levelName = 'ASGR',
                x = -403, 
                y = -1233, 
                z = 8950,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item133 = {        
                levelName = 'ASGR',
                x = -562, 
                y = 399, 
                z = 8091,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item134 = {        
                levelName = 'ASGR',
                x = 267, 
                y = 668, 
                z = 7040,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item135 = {        
                levelName = 'ASGR',
                x = 99, 
                y = 756, 
                z = 5515,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item136 = {        
                levelName = 'ASGR',
                x = -845, 
                y = 30, 
                z = 6736,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item137 = {        
                levelName = 'ASGR',
                x = 981, 
                y = 298, 
                z = 2902,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item138 = {        
                levelName = 'ASGR',
                x = -854, 
                y = 323, 
                z = 2986,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item139 = {        
                levelName = 'ASGR',
                x = 2389, 
                y = -54, 
                z = 7041,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item140 = {        
                levelName = 'ASGR',
                x = 2110, 
                y = 305, 
                z = 2224,
                ox = 0,
                oy = 0,
                oz = 0,
            },

            --ASCO, Lower Floors
            item141 = {        
                levelName = 'ASCO',
                x = 558, 
                y = 948, 
                z = 599,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item142 = {        
                levelName = 'ASCO',
                x = -866, 
                y = 208, 
                z = 1586,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item143 = {        
                levelName = 'ASCO',
                x = -1040, 
                y = 1178, 
                z = 1998,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item144 = {        
                levelName = 'ASCO',
                x = -1495, 
                y = 1206, 
                z = 1267,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item145 = {        
                levelName = 'ASCO',
                x = 319, 
                y = 955, 
                z = 2184,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item146 = {        
                levelName = 'ASCO',
                x = -2302, 
                y = 1249, 
                z = 93,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item147 = {        
                levelName = 'ASCO',
                x = -175, 
                y = 814, 
                z = -710,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item148 = {        
                levelName = 'ASCO',
                x = 1570, 
                y = 514, 
                z = -782,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item149 = {        
                levelName = 'ASCO',
                x = -1394, 
                y = 2209, 
                z = -283,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            
            --ASUP, Upper Floors
            item150 = {        
                levelName = 'ASUP',
                x = -1723, 
                y = 3617, 
                z = 2137,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item151 = {        
                levelName = 'ASUP',
                x = -2719, 
                y = 4300, 
                z = 3080,
                ox = 0,
                oy = 137,
                oz = 0,
            },
            item152 = {        
                levelName = 'ASUP',
                x = -357, 
                y = 4380, 
                z = 3650,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item153 = {        
                levelName = 'ASUP',
                x = -1547, 
                y = 3633, 
                z = 831,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item154 = {        
                levelName = 'ASUP',
                x = -457, 
                y = 4299, 
                z = -3572,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item155 = {        
                levelName = 'ASUP',
                x = 1026, 
                y = 4971, 
                z = -2473,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item156 = {        
                levelName = 'ASUP',
                x = 1771, 
                y = 5214, 
                z = -2217,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item157 = {        
                levelName = 'ASUP',
                x = 2421, 
                y = 6422, 
                z = -2933,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item158 = {        
                levelName = 'ASUP',
                x = 1296, 
                y = 6544, 
                z = -3663,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item159 = {        
                levelName = 'ASUP',
                x = -1954, 
                y = 6401, 
                z = -3281,
                ox = 0,
                oy = -47,
                oz = 0,
            },
            item160 = {        
                levelName = 'ASUP',
                x = -969, 
                y = 7468, 
                z = -3794,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item161 = {        
                levelName = 'ASUP',
                x = -1649, 
                y = 8398, 
                z = -2675,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item162 = {        
                levelName = 'ASUP',
                x = 151, 
                y = 10061, 
                z = -1786,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item163 = {        
                levelName = 'ASUP',
                x = -121, 
                y = 10762, 
                z = -466,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item164 = {        
                levelName = 'ASUP',
                x = -312, 
                y = 11220, 
                z = -2910,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item165 = {        
                levelName = 'ASUP',
                x = 344, 
                y = 12358, 
                z = -428,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item166 = {        
                levelName = 'ASUP',
                x = -1385, 
                y = 13121, 
                z = -1413,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item167 = {        
                levelName = 'ASUP',
                x = 1893, 
                y = 13857, 
                z = 740,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item168 = {        
                levelName = 'ASUP',
                x = -1120, 
                y = 14462, 
                z = -903,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item169 = {        
                levelName = 'ASUP',
                x = -676, 
                y = 15603, 
                z = -1402,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item170 = {        
                levelName = 'ASUP',
                x = 1226, 
                y = 17755, 
                z = -240,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item171 = {        
                levelName = 'ASUP',
                x = 994, 
                y = 17737, 
                z = -148,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item172 = {        
                levelName = 'ASUP',
                x = 830, 
                y = 18831, 
                z = -1992,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item173 = {        
                levelName = 'ASUP',
                x = 1350, 
                y = 19200, 
                z = -2349,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item174 = {        
                levelName = 'ASUP',
                x = 563, 
                y = 20956, 
                z = -475,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item175 = {        
                levelName = 'ASUP',
                x = 74, 
                y = 22016, 
                z = -2318,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            
            --ASLB, Lobato's Lab
            item176 = {        
                levelName = 'ASLB',
                x = -304, 
                y = 1509, 
                z = 178,
                ox = 0,
                oy = 165,
                oz = 0,
            },
            item177 = {        
                levelName = 'ASLB',
                x = -682, 
                y = 1347, 
                z = -473,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item178 = {        
                levelName = 'ASLB',
                x = 480, 
                y = 2298, 
                z = -766,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item179 = {        
                levelName = 'ASLB',
                x = 1512, 
                y = 2869, 
                z = -1127,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item180 = {        
                levelName = 'ASLB',
                x = 1357, 
                y = 3182, 
                z = -183,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item181 = {        
                levelName = 'ASLB',
                x = -1768, 
                y = 2951, 
                z = 900,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item182 = {        
                levelName = 'ASLB',
                x = -319, 
                y = 3440, 
                z = 1165,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item183 = {        
                levelName = 'ASLB',
                x = 142, 
                y = 3364, 
                z = -438,
                ox = 0,
                oy = 0,
                oz = 0,
            },

            --*******************************************************--
            --BB, BASIC BRAINING

            --BBA1, Opening Level
            item184 = {        
                levelName = 'BBA1',
                x = -8089, 
                y = -2453, 
                z = 7797,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item185 = {        
                levelName = 'BBA1',
                x = -6261, 
                y = -2491, 
                z = 7933,
                ox = 0,
                oy = -90,
                oz = 0,
            },
            item186 = {        
                levelName = 'BBA1',
                x = -4451, 
                y = -1115, 
                z = 7062,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item187 = {        
                levelName = 'BBA1',
                x = 6656, 
                y = -104, 
                z = 5872,
                ox = 0,
                oy = -160,
                oz = 0,
            },

            --BBA2, After Plane Drop
            item188 = {        
                levelName = 'BBA2',
                x = -3763, 
                y = 9543, 
                z = -4986,
                ox = 0,
                oy = -75,
                oz = 0,
            },
            item189 = {        
                levelName = 'BBA2',
                x = -407, 
                y = 9695, 
                z = -2482,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item190 = {        
                levelName = 'BBA2',
                x = -435, 
                y = 9601, 
                z = 27,
                ox = 0,
                oy = -145,
                oz = 0,
            },
            item191 = {        
                levelName = 'BBA2',
                x = 2247, 
                y = 10327, 
                z = 4054,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item192 = {        
                levelName = 'BBA2',
                x = -599, 
                y = -128, 
                z = 9708,
                ox = 0,
                oy = 99,
                oz = 0,
            },
            item193 = {        
                levelName = 'BBA2',
                x = -927, 
                y = 2559, 
                z = 11824,
                ox = 0,
                oy = -111,
                oz = 0,
            },
            item194 = {        
                levelName = 'BBA2',
                x = -2457, 
                y = 3034, 
                z = 14533,
                ox = 0,
                oy = 136,
                oz = 0,
            },
            item195 = {        
                levelName = 'BBA2',
                x = -1744, 
                y = 3794, 
                z = 14358,
                ox = 0,
                oy = 136,
                oz = 0,
            },            

            --BBLT, Finishing Podium
            item196 = {        
                levelName = 'BBLT',
                x = -6407, 
                y = -1931, 
                z = 5691,
                ox = 0,
                oy = 153,
                oz = 0,
            },
            item197 = {        
                levelName = 'BBLT',
                x = -6864, 
                y = -1914, 
                z = 5331,
                ox = 0,
                oy = 153,
                oz = 0,
            },
            --CASA, BB Complete
            item198 = {        
                levelName = 'CASA',
                x = -12954, 
                y = 11560, 
                z = -5523,
                ox = 0,
                oy = -158,
                oz = 0,
                puzzle = 'bbDone'
            },            

            --*******************************************************--

            --SA, SASHA'S SHOOTING GALLERY
            --SACU           
            --Cube Face One
            item199 = {        
                levelName = 'SACU',
                x = -7, 
                y = 487, 
                z = -28,
                ox = 0,
                oy = -42,
                oz = 0,
                puzzle = 'face1item1'
            },
            item200 = {        
                levelName = 'SACU',
                x = -262, 
                y = 564, 
                z = -378,
                ox = 0,
                oy = 54,
                oz = 0,
                puzzle = 'face1item2'
            },
            item201 = {        
                levelName = 'SACU',
                x = -1371, 
                y = 751, 
                z = 513,
                ox = -33,
                oy = 103,
                oz = -32,
                puzzle = 'face1item3'
            },
            item202 = {        
                levelName = 'SACU',
                x = -1455, 
                y = 5, 
                z = 491,
                ox = 0,
                oy = -37,
                oz = 0,
                puzzle = 'face1item4'
            },
            item203 = {        
                levelName = 'SACU',
                x = 1832, 
                y = 799, 
                z = -1348,
                ox = 0,
                oy = 0,
                oz = 0,
                puzzle = 'face1item5'
            },
            item204 = {        
                levelName = 'SACU',
                x = -274, 
                y = 1748, 
                z = -1546,
                ox = 0,
                oy = -121,
                oz = 0,
                puzzle = 'face1item6'
            },

            --Cube Face Two
            item205 = {        
                levelName = 'SACU',
                x = 2021, 
                y = -1558, 
                z = 753,
                ox = 0,
                oy = 18,
                oz = -90,
                puzzle = 'face2item1'
            },
            item206 = {        
                levelName = 'SACU',
                x = 3920, 
                y = -900, 
                z = 2650,
                ox = 0,
                oy = 76,
                oz = -90,
                puzzle = 'face2item2'
            },
            item207 = {        
                levelName = 'SACU',
                x = 4187, 
                y = -1867, 
                z = -1747,
                ox = 0,
                oy = 0,
                oz = -90,
                puzzle = 'face2item3'
            },

            --Cube Face Three
            item208 = {        
                levelName = 'SACU',
                x = -1984, 
                y = -1913, 
                z = 0,
                ox = 178,
                oy = 0,
                oz = -90,
                puzzle = 'face3item1'
            },
            item209 = {        
                levelName = 'SACU',
                x = 19, 
                y = -2128, 
                z = -1848,
                ox = 90,
                oy = 179,
                oz = 61,
                puzzle = 'face3item2'
            },
            item210 = {        
                levelName = 'SACU',
                x = -291, 
                y = -538, 
                z = -2863,
                ox = 87,
                oy = 180,
                oz = 3,
                puzzle = 'face3item3'
            },
            item211 = {        
                levelName = 'SACU',
                x = 1853, 
                y = -2948, 
                z = -4743,
                ox = -90,
                oy = 0,
                oz = 0,
                puzzle = 'face3item4'
            },
          
            --Cube Face Four
            item212 = {        
                levelName = 'SACU',
                x = 398, 
                y = -4056, 
                z = -843,
                ox = 180,
                oy = 0,
                oz = 0,
                puzzle = 'face4item1'
            },
            item213 = {        
                levelName = 'SACU',
                x = 379, 
                y = -4962, 
                z = 422,
                ox = 174,
                oy = 131,
                oz = -8,
                puzzle = 'face4item2'
            },
            item214 = {        
                levelName = 'SACU',
                x = 273, 
                y = -5024, 
                z = -148,
                ox = 180,
                oy = 0,
                oz = 0,
                puzzle = 'face4item3'
            },

            --CASA, SA Complete
            item215 = {        
                levelName = 'CASA',
                x = -13922, 
                y = 11352, 
                z = -4566,
                ox = 0,
                oy = -90,
                oz = 0,
                puzzle = 'saDone'
            },

            --*******************************************************--
            --MI, MILLA'S DANCE PARTY

            --MIFL, Starting area
            item216 = {        
                levelName = 'MIFL',
                x = -19249, 
                y = 7142, 
                z = 29935,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item217 = {        
                levelName = 'MIFL',
                x = -19976, 
                y = 10155, 
                z = 24167,
                ox = 0,
                oy = -81,
                oz = 0,
            },
            item218 = {        
                levelName = 'MIFL',
                x = -23438, 
                y = 11229, 
                z = 21816,
                ox = 0,
                oy = 24,
                oz = 0,
            },
            item219 = {        
                levelName = 'MIFL',
                x = -20143, 
                y = 11734, 
                z = 26556,
                ox = 0,
                oy = -159,
                oz = 0,
            },
            item220 = {        
                levelName = 'MIFL',
                x = -18415, 
                y = 14813, 
                z = 26121,
                ox = 0,
                oy = 71,
                oz = 0,
            },
            item221 = {        
                levelName = 'MIFL',
                x = -22356, 
                y = 15996, 
                z = 26767,
                ox = 0,
                oy = 134,
                oz = 0,
            },
            item222 = {        
                levelName = 'MIFL',
                x = -18472, 
                y = 22382, 
                z = 22091,
                ox = 0,
                oy = -30,
                oz = 0,
            },
            item223 = {        
                levelName = 'MIFL',
                x = -19528, 
                y = 23610, 
                z = 29712,
                ox = 0,
                oy = 125,
                oz = 0,
            },
            item224 = {        
                levelName = 'MIFL',
                x = -22571, 
                y = 23009, 
                z = 32232,
                ox = 0,
                oy = 125,
                oz = 0,
            },
            item225 = {        
                levelName = 'MIFL',
                x = -21000, 
                y = 29640, 
                z = 32184,
                ox = 0,
                oy = -89,
                oz = 0,
            },

            --MILL, After Race
            item226 = {        
                levelName = 'MILL',
                x = 17393, 
                y = -5479, 
                z = -21342,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item227 = {        
                levelName = 'MILL',
                x = 18938, 
                y = -1889, 
                z = -18444,
                ox = 0,
                oy = -164,
                oz = 0,
            },
            item228 = {        
                levelName = 'MILL',
                x = 19431, 
                y = -1669, 
                z = -22105,
                ox = 0,
                oy = -76,
                oz = 0,
            },
            item229 = {        
                levelName = 'MILL',
                x = 21816, 
                y = -1771, 
                z = -24854,
                ox = 0,
                oy = -50,
                oz = 0,
            },

            --CASA, MI Complete
            item230 = {        
                levelName = 'CASA',
                x = -10778, 
                y = 11432, 
                z = -4760,
                ox = 0,
                oy = 109,
                oz = 0,
                puzzle = 'miDone'
            },

            --*******************************************************--

            --NI, Brain Tumbler Experiment

            --NIMP, Main Level
            item231 = {        
                levelName = 'NIMP',
                x = 34503, 
                y = 23, 
                z = 993,
                ox = 0,
                oy = -11,
                oz = 0,
            },
            item232 = {        
                levelName = 'NIMP',
                x = -2209, 
                y = -3186, 
                z = -3497,
                ox = 0,
                oy = 46,
                oz = 0,
            },
            item233 = {        
                levelName = 'NIMP',
                x = 2693, 
                y = -645, 
                z = -8500,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item234 = {        
                levelName = 'NIMP',
                x = 1900, 
                y = -604, 
                z = -12903,
                ox = 0,
                oy = 9,
                oz = 0,
            },
            item235 = {        
                levelName = 'NIMP',
                x = 545, 
                y = 716, 
                z = -13798,
                ox = 0,
                oy = -62,
                oz = 0,
            },
            item236 = {        
                levelName = 'NIMP',
                x = -1805, 
                y = -228, 
                z = -16247,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item237 = {        
                levelName = 'NIMP',
                x = 650, 
                y = -510, 
                z = -21602,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item238 = {        
                levelName = 'NIMP',
                x = 4077, 
                y = 426, 
                z = -22925,
                ox = 0,
                oy = 158,
                oz = 0,
            },
            item239 = {        
                levelName = 'NIMP',
                x = 604, 
                y = 1113, 
                z = -22266,
                ox = 0,
                oy = 124,
                oz = 0,
            },
            item240 = {        
                levelName = 'NIMP',
                x = 3869, 
                y = -82, 
                z = -18945,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item241 = {        
                levelName = 'NIMP',
                x = 13527, 
                y = 293, 
                z = -12247,
                ox = 0,
                oy = 119,
                oz = 0,
            },
            item242 = {        
                levelName = 'NIMP',
                x = 12707, 
                y = 421, 
                z = -11504,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item243 = {        
                levelName = 'NIMP',
                x = 13624, 
                y = 430, 
                z = -8900,
                ox = 0,
                oy = -152,
                oz = 0,
            },

            --CASA, NI Complete
            item244 = {        
                levelName = 'CASA',
                x = -11139, 
                y = 11486, 
                z = -5505,
                ox = 0,
                oy = 157,
                oz = 0,
                puzzle = 'niDone'
            },


            --*******************************************************--

            --LO, LUNGFISHOPOLIS

            --LOMA, Main City
            item245 = {        
                levelName = 'LOMA',
                x = -1665, 
                y = 916, 
                z = 2164,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item246 = {        
                levelName = 'LOMA',
                x = 224, 
                y = 4, 
                z = -41,
                ox = 0,
                oy = -132,
                oz = 0,
            },
            item247 = {        
                levelName = 'LOMA',
                x = 2328, 
                y = 685, 
                z = -3129,
                ox = 0,
                oy = 15,
                oz = 0,
            },
            item248 = {        
                levelName = 'LOMA',
                x = -2233, 
                y = 11, 
                z = -5273,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item249 = {        
                levelName = 'LOMA',
                x = -1843, 
                y = 0, 
                z = -5811,
                ox = 0,
                oy = 119,
                oz = 0,
            },
            item250 = {        
                levelName = 'LOMA',
                x = -545, 
                y = 7, 
                z = -7681,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item251 = {        
                levelName = 'LOMA',
                x = 8421, 
                y = 2092, 
                z = -4772,
                ox = 0,
                oy = -12,
                oz = 0,
            },
            item252 = {        
                levelName = 'LOMA',
                x = 8442, 
                y = 2076, 
                z = -712,
                ox = 0,
                oy = 123,
                oz = 0,
            },
            item253 = {        
                levelName = 'LOMA',
                x = 7971, 
                y = 2402, 
                z = 106,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item254 = {        
                levelName = 'LOMA',
                x = 10615, 
                y = 3051, 
                z = -6002,
                ox = 0,
                oy = -58,
                oz = 0,
            },
            item255 = {        
                levelName = 'LOMA',
                x = 12049, 
                y = 2099, 
                z = -6628,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item256 = {        
                levelName = 'LOMA',
                x = 16172, 
                y = 2595, 
                z = -9585,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item257 = {        
                levelName = 'LOMA',
                x = 17297, 
                y = 2081, 
                z = -10498,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item258 = {        
                levelName = 'LOMA',
                x = 17657, 
                y = 2761, 
                z = -10112,
                ox = 0,
                oy = -65,
                oz = 0,
            },
            item259 = {        
                levelName = 'LOMA',
                x = 18667, 
                y = 2196, 
                z = -12753,
                ox = 0,
                oy = -9,
                oz = 0,
            },
            item260 = {        
                levelName = 'LOMA',
                x = 21356, 
                y = 4471, 
                z = -11694,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item261 = {        
                levelName = 'LOMA',
                x = 21818, 
                y = 4446, 
                z = -9950,
                ox = 0,
                oy = -21,
                oz = 0,
            },
            
            --LOCB, Kochamara Boss Fight
            item262 = {        
                levelName = 'LOCB',
                x = 239, 
                y = 396, 
                z = -648,
                ox = 0,
                oy = -58,
                oz = 0,
            },
            item263 = {        
                levelName = 'LOCB',
                x = 310, 
                y = 447, 
                z = 592,
                ox = 0,
                oy = -117,
                oz = 0,
            },

            --CASA, LO Complete
            item264 = {        
                levelName = 'CASA',
                x = -11962, 
                y = 11615, 
                z = -5630,
                ox = 0,
                oy = -170,
                oz = 0,
                puzzle = 'loDone'
            },
            

            --*******************************************************--
            --MM, MILKMAN CONSPIRACY

            --MMI1, Neighborhood
            item265 = {        
                levelName = 'MMI1',
                x = 16807, 
                y = 9324, 
                z = -26821,
                ox = 88,
                oy = 0,
                oz = 89,
            },
            item266 = {        
                levelName = 'MMI1',
                x = 15603, 
                y = 1464, 
                z = -28180,
                ox = 0,
                oy = -89,
                oz = 0,
            },
            item267 = {        
                levelName = 'MMI1',
                x = 14012, 
                y = 1472, 
                z = -27498,
                ox = 0,
                oy = 151,
                oz = -3,
            },
            item268 = {        
                levelName = 'MMI1',
                x = 46391, 
                y = -29286, 
                z = -17896,
                ox = -143,
                oy = 168,
                oz = -53,
            },
            item269 = {        
                levelName = 'MMI1',
                x = 49303, 
                y = -32124, 
                z = -12316,
                ox = 4,
                oy = 38,
                oz = 0,
            },
            item270 = {        
                levelName = 'MMI1',
                x = 52485, 
                y = -29921, 
                z = -11122,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item271 = {        
                levelName = 'MMI1',
                x = 52339, 
                y = -28808, 
                z = -10817,
                ox = -19,
                oy = 44,
                oz = 75,
            },
            item272 = {        
                levelName = 'MMI1',
                x = 51818, 
                y = -31078, 
                z = -5866,
                ox = 88,
                oy = -67,
                oz = 36,
            },
            item273 = {        
                levelName = 'MMI1',
                x = 54275, 
                y = -33701, 
                z = -2863,
                ox = 161,
                oy = 33,
                oz = -85,
            },
            item274 = {        
                levelName = 'MMI1',
                x = 54655, 
                y = -34030, 
                z = -1600,
                ox = -166,
                oy = -138,
                oz = -78,
            },
            item275 = {        
                levelName = 'MMI1',
                x = 55736, 
                y = -38952, 
                z = -4843,
                ox = -156,
                oy = 172,
                oz = -65,
            },
            item276 = {        
                levelName = 'MMI1',
                x = 49127, 
                y = -31686, 
                z = 2498,
                ox = -172,
                oy = 30,
                oz = -86,
            },
            item277 = {        
                levelName = 'MMI1',
                x = 49643, 
                y = -26013, 
                z = -496,
                ox = 27,
                oy = -25,
                oz = -3,
            },
            item278 = {        
                levelName = 'MMI1',
                x = 48881, 
                y = -23596, 
                z = 2322,
                ox = -127,
                oy = 168,
                oz = 16,
            },
            item279 = {        
                levelName = 'MMI1',
                x = 49974, 
                y = -23919, 
                z = 1151,
                ox = -102,
                oy = 141,
                oz = 66,
            },
            item280 = {        
                levelName = 'MMI1',
                x = -12940, 
                y = 3048, 
                z = -28723,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item281 = {        
                levelName = 'MMI1',
                x = 46881, 
                y = -32509, 
                z = -8474,
                ox = -21,
                oy = 20,
                oz = 8,
            },
            item282 = {        
                levelName = 'MMI1',
                x = 18174, 
                y = 1410, 
                z = -27787,
                ox = 1,
                oy = 5,
                oz = 0,
            },
            item283 = {        
                levelName = 'MMI1',
                x = 19236, 
                y = 1462, 
                z = -27810,
                ox = 0,
                oy = -77,
                oz = 0,
            },
            item284 = {        
                levelName = 'MMI1',
                x = 38276, 
                y = -36118, 
                z = -9751,
                ox = -13,
                oy = 50,
                oz = -4,
            },
            item285 = {        
                levelName = 'MMI1',
                x = 37993, 
                y = -38043, 
                z = -5503,
                ox = -34,
                oy = 179,
                oz = 11,
            },
            item286 = {        
                levelName = 'MMI1',
                x = 37449, 
                y = -36123, 
                z = -8403,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            
            --MMI2, Book Depository
            item287 = {        
                levelName = 'MMI2',
                x = 42685, 
                y = -30805, 
                z = 4210,
                ox = -2,
                oy = -4,
                oz = 0,
            },
            
            --CASA, MM Complete
            item288 = {        
                levelName = 'CASA',
                x = -11357, 
                y = 11476, 
                z = -3457,
                ox = 0,
                oy = 38,
                oz = 0,
                puzzle = 'mmDone'
            },

            --*******************************************************--
            --TH, GLORIA'S THEATER

            --THMS, Main Stage
            item289 = {        
                levelName = 'THMS',
                x = 2634, 
                y = 619, 
                z = -2170,
                ox = 0,
                oy = -107,
                oz = 0,
            },
            item290 = {        
                levelName = 'THMS',
                x = 1882, 
                y = 1329, 
                z = -4238,
                ox = 0,
                oy = -63,
                oz = 0,
            },
            item291 = {        
                levelName = 'THMS',
                x = -2141, 
                y = -250, 
                z = -1356,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item292 = {        
                levelName = 'THMS',
                x = 1993, 
                y = 0, 
                z = 910,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item293 = {        
                levelName = 'THMS',
                x = 2354, 
                y = 0, 
                z = 2076,
                ox = 0,
                oy = -116,
                oz = 0,
            },
            item294 = {        
                levelName = 'THMS',
                x = -3133, 
                y = 421, 
                z = 1999,
                ox = 0,
                oy = -70,
                oz = 0,
            },
            item295 = {        
                levelName = 'THMS',
                x = -2673, 
                y = 1467, 
                z = 3361,
                ox = 0,
                oy = -125,
                oz = 0,
            },
            item296 = {        
                levelName = 'THMS',
                x = -4366, 
                y = 1467, 
                z = 3354,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item297 = {        
                levelName = 'THMS',
                x = -4017, 
                y = 2198, 
                z = 3492,
                ox = 0,
                oy = -79,
                oz = 0,
            },
            item298 = {        
                levelName = 'THMS',
                x = -5320, 
                y = 282, 
                z = 1377,
                ox = 0,
                oy = 135,
                oz = 0,
            },

            --THCW, Catwalks
            item299 = {        
                levelName = 'THCW',
                x = -1692, 
                y = -1766, 
                z = -4130,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item300 = {        
                levelName = 'THCW',
                x = 424, 
                y = -516, 
                z = -5335,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item301 = {        
                levelName = 'THCW',
                x = -1297, 
                y = -509, 
                z = -5263,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item302 = {        
                levelName = 'THCW',
                x = -437, 
                y = -324, 
                z = -6010,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item303 = {        
                levelName = 'THCW',
                x = -308, 
                y = 302, 
                z = -6002,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item304 = {        
                levelName = 'THCW',
                x = -3463, 
                y = 877, 
                z = -2246,
                ox = 0,
                oy = 179,
                oz = 0,
            },
            item305 = {        
                levelName = 'THCW',
                x = 554, 
                y = 2881, 
                z = -2672,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item306 = {        
                levelName = 'THCW',
                x = 2999, 
                y = 1, 
                z = 2721,
                ox = 0,
                oy = -169,
                oz = 0,
            },
            item307 = {        
                levelName = 'THCW',
                x = 966, 
                y = -1418, 
                z = -4787,
                ox = 0,
                oy = -177,
                oz = 0,
            },

            --CASA,TH Complete
            item308 = {        
                levelName = 'CASA',
                x = -13645, 
                y = 11449, 
                z = -5125,
                ox = 0,
                oy = -122,
                oz = 0,
                puzzle = 'thDone'
            },

            --*******************************************************--
            --WW, WATERLOO WORLD

            --WWMA, Whole Level
            item309 = {        
                levelName = 'WWMA',
                x = -43786, 
                y = 9006, 
                z = 5234,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item310 = {        
                levelName = 'WWMA',
                x = -44408, 
                y = 8978, 
                z = 5315,
                ox = 0,
                oy = 14,
                oz = 4,
            },
            item311 = {        
                levelName = 'WWMA',
                x = -27225, 
                y = 140, 
                z = 4925,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item312 = {        
                levelName = 'WWMA',
                x = 13099, 
                y = -17850, 
                z = 1858,
                ox = 0,
                oy = -15,
                oz = 0,
            },
            item313 = {        
                levelName = 'WWMA',
                x = 16820, 
                y = -18717, 
                z = 4074,
                ox = 0,
                oy = 180,
                oz = 0,
            },
            item314 = {        
                levelName = 'WWMA',
                x = 20406, 
                y = -19699, 
                z = 9934,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item315 = {        
                levelName = 'WWMA',
                x = 28368, 
                y = -18617, 
                z = 12753,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item316 = {        
                levelName = 'WWMA',
                x = 29109, 
                y = -19481, 
                z = 12767,
                ox = 0,
                oy = 18,
                oz = 0,
            },
            item317 = {        
                levelName = 'WWMA',
                x = 10401, 
                y = -18337, 
                z = 15650,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item318 = {        
                levelName = 'WWMA',
                x = 23724, 
                y = -17634, 
                z = 12876,
                ox = 0,
                oy = 173,
                oz = 0,
            },
            item319 = {        
                levelName = 'WWMA',
                x = 20285, 
                y = -18438, 
                z = 20588,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item320 = {        
                levelName = 'WWMA',
                x = 19216, 
                y = -18331, 
                z = 23129,
                ox = 0,
                oy = -15,
                oz = 0,
            },
            item321 = {        
                levelName = 'WWMA',
                x = 20430, 
                y = -19300, 
                z = 24700,
                ox = 0,
                oy = 86,
                oz = 0,
            },
            item322 = {        
                levelName = 'WWMA',
                x = 17248, 
                y = -19397, 
                z = 9077,
                ox = 0,
                oy = -61,
                oz = 0,
            },
            item323 = {        
                levelName = 'WWMA',
                x = 21656, 
                y = -20134, 
                z = 2503,
                ox = 0,
                oy = 37,
                oz = 0,
            },
            item324 = {        
                levelName = 'WWMA',
                x = 25559, 
                y = -18312, 
                z = 20976,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item325 = {        
                levelName = 'WWMA',
                x = 23066, 
                y = -18398, 
                z = 18601,
                ox = 0,
                oy = 116,
                oz = 0,
            },
            --Musket Haybale location
            item326 = {        
                levelName = 'WWMA',
                x = -10000, 
                y = -25000, 
                z = -10000,
                ox = 0,
                oy = 0,
                oz = 0,
                puzzle = 'haybale'
            },
            --Carpenter Helped
            item327 = {        
                levelName = 'WWMA',
                x = -10000, 
                y = -25000, 
                z = -10000,
                ox = 0,
                oy = 68,
                oz = 0,
                puzzle = 'CarpHelp'
            },
            --Peasant 1 Helped
            item328 = {        
                levelName = 'WWMA',
                x = -10000, 
                y = -25000, 
                z = -10000,
                ox = 0,
                oy = -179,
                oz = 0,
                puzzle = 'p1Help'
            },
            --Knight Helped
            item329 = {        
                levelName = 'WWMA',
                x = -10000, 
                y = -25000, 
                z = -10000,
                ox = 0,
                oy = -55,
                oz = 0,
                puzzle = 'KnightHelp'
            },
            --Peasant 2 Helped
            item330 = {        
                levelName = 'WWMA',
                x = -10000, 
                y = -25000, 
                z = -10000,
                ox = 0,
                oy = 99,
                oz = 0,
                puzzle = 'p2Help'
            },
            --Peasant 3 Helped
            item331 = {        
                levelName = 'WWMA',
                x = -10000, 
                y = -25000, 
                z = -10000,
                ox = 0,
                oy = -69,
                oz = 0,
                puzzle = 'p3Help'
            },

            --CASA, WW Complete
            item332 = {        
                levelName = 'CASA',
                x = -10758, 
                y = 11438, 
                z = -4170,
                ox = 0,
                oy = 85,
                oz = 0,
                puzzle = 'wwDone'
            },

            --*******************************************************--
            --BV, BLACK VELVETOPIA

            --BVRB, Main Streets
            item333 = {        
                levelName = 'BVRB',
                x = 1104, 
                y = 136, 
                z = 1266,
                ox = 0,
                oy = -43,
                oz = 0,
            },
            item334 = {        
                levelName = 'BVRB',
                x = -2284, 
                y = 920, 
                z = -3038,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item335 = {        
                levelName = 'BVRB',
                x = -6709, 
                y = 2471, 
                z = -2290,
                ox = 0,
                oy = -168,
                oz = 0,
            },
            item336 = {        
                levelName = 'BVRB',
                x = -3152, 
                y = 2856, 
                z = -11986,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item337 = {        
                levelName = 'BVRB',
                x = -7967, 
                y = -72, 
                z = -9302,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item338 = {        
                levelName = 'BVRB',
                x = 8, 
                y = 150, 
                z = -2813,
                ox = 0,
                oy = -27,
                oz = 0,
            },
            item339 = {        
                levelName = 'BVRB',
                x = -10083, 
                y = 1028, 
                z = 1218,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item340 = {        
                levelName = 'BVRB',
                x = -11151, 
                y = 2332, 
                z = 231,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item341 = {        
                levelName = 'BVRB',
                x = 2032, 
                y = 2680, 
                z = -6940,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item342 = {        
                levelName = 'BVRB',
                x = -583, 
                y = 1946, 
                z = -5915,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item343 = {        
                levelName = 'BVRB',
                x = -2112, 
                y = 1943, 
                z = -286,
                ox = 0,
                oy = 177,
                oz = 0,
            },
            item344 = {        
                levelName = 'BVRB',
                x = 827, 
                y = 1624, 
                z = -4369,
                ox = 0,
                oy = 0,
                oz = 0,
            },


            --BVES, Edgar's Sanctuary
            item345 = {        
                levelName = 'BVES',
                x = -1062, 
                y = 571, 
                z = -2330,
                ox = 0,
                oy = 20,
                oz = 0,
            },
            item346 = {        
                levelName = 'BVES',
                x = 2310, 
                y = 32, 
                z = 1207,
                ox = 0,
                oy = -161,
                oz = 0,
            },
            --Tiger Wrestler
            item347 = {        
                levelName = 'BVES',
                x = -2125, 
                y = 14, 
                z = -664,
                ox = 0,
                oy = -107,
                oz = 0,
                puzzle = 'tiger'
            },
            --Dragon Wrestler
            item348 = {        
                levelName = 'BVES',
                x = -154, 
                y = 17, 
                z = 2249,
                ox = 0,
                oy = -11,
                oz = 0,
                puzzle = 'dragon'
            },
            --Eagle Wrestler
            item349 = {        
                levelName = 'BVES',
                x = 680, 
                y = 13, 
                z = -2102,
                ox = 0,
                oy = 165,
                oz = 0,
                puzzle = 'eagle'
            },
            --Cobra Wrestler
            item350 = {        
                levelName = 'BVES',
                x = 2149, 
                y = 15, 
                z = 459,
                ox = 0,
                oy = 71,
                oz = 0,
                puzzle = 'cobra'
            },

            --CASA, BV Complete
            item351 = {        
                levelName = 'CASA',
                x = -13691, 
                y = 11326, 
                z = -3785,
                ox = 0,
                oy = -54,
                oz = 0,
                puzzle = 'bvDone'
            },

            --*******************************************************--
            --MC, MEAT CIRCUS

            --MCTC, Main Level
            item352 = {        
                levelName = 'MCTC',
                x = 248, 
                y = 766, 
                z = 539,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item353 = {        
                levelName = 'MCTC',
                x = -70, 
                y = -39, 
                z = -2803,
                ox = 0,
                oy = -3,
                oz = 0,
            },
            item354 = {        
                levelName = 'MCTC',
                x = 294, 
                y = -596, 
                z = -4822,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item355 = {        
                levelName = 'MCTC',
                x = 1719, 
                y = -23392, 
                z = -1626,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item356 = {        
                levelName = 'MCTC',
                x = 1150, 
                y = -20270, 
                z = -1840,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item357 = {        
                levelName = 'MCTC',
                x = -2223, 
                y = -14639, 
                z = -3233,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item358 = {        
                levelName = 'MCTC',
                x = -2163, 
                y = -14647, 
                z = -3689,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item359 = {        
                levelName = 'MCTC',
                x = 1848, 
                y = 3543, 
                z = 5571,
                ox = 0,
                oy = 178,
                oz = 0,
            },
            item360 = {        
                levelName = 'MCTC',
                x = 3856, 
                y = 3594, 
                z = 4937,
                ox = 0,
                oy = -69,
                oz = 0,
            },
            item361 = {        
                levelName = 'MCTC',
                x = -3487, 
                y = 2103, 
                z = 6444,
                ox = 0,
                oy = 0,
                oz = 0,
            },
            item362 = {        
                levelName = 'MCTC',
                x = -943, 
                y = -1373, 
                z = 14417,
                ox = 8,
                oy = 42,
                oz = 24,
            },
            
            --*******************************************************--

        
        }
        self.positionsList = posTable
        
    end
    return Ob
end